// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twbbnowdqbeplnfvglek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3YmJub3dkcWJlcGxuZnZnbGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NjI5OTAsImV4cCI6MjA5OTUzODk5MH0.jV8hW9UoeeeQ7H05Zs4GkiDcc6oRgm56W68kIvUKYtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});